version: '3'
services:
  demo-client:
    build:
      context: ./caminho/para/demo-client
    ports:
      - "4200:4200"
    depends_on:
      - demo-api

  demo-api:
    build:
      context: ./caminho/para/demo-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
